### ISSUE TITLE
如何使用带有密码认证的Redis缓存

### ISSUE THREAD

**Issue by aaro-n** [ArtalkJS/ArtalkGo#33]
正在使用的Redis带有密码认证，ArtalkGo在使用redis做缓存时，如何设置？
密码认证无法关闭。
例子
Redis访问链接：`redis://default:YOCnibb5ijA9eltMBI1RGb2SVBFEdN56@redis-12875.c57.us-east-1-4.ec2.cloud.redislabs.com:12875`
如何配置？
```
# 缓存
cache:
  type: "builtin" # 支持 redis, memcache, builtin (自带缓存)
  expires: 30     # 缓存过期时间 (单位：分钟)
  warm_up: false  # 程序启动时预热缓存
  server: ""      # 连接缓存服务器 (例如："localhost:6379")
```
